// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEgOBFCQiYeO7FlkPrvArHRTtYrImFsJY',
    appId: '1:591172655321:web:9839e83cffc12d9bc1c6c8',
    messagingSenderId: '591172655321',
    projectId: 'hostelmate-e15a4',
    authDomain: 'hostelmate-e15a4.firebaseapp.com',
    storageBucket: 'hostelmate-e15a4.firebasestorage.app',
    measurementId: 'G-CPEJG7Q9E8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF66iCnly_jA5xVMmExbyiK4ON4pYqECE',
    appId: '1:591172655321:android:aeca610a42d393a5c1c6c8',
    messagingSenderId: '591172655321',
    projectId: 'hostelmate-e15a4',
    storageBucket: 'hostelmate-e15a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI8uNO-RMyHBRxtVFzkR_Pv3SRI9SAqC0',
    appId: '1:591172655321:ios:e3d0279007225fe9c1c6c8',
    messagingSenderId: '591172655321',
    projectId: 'hostelmate-e15a4',
    storageBucket: 'hostelmate-e15a4.firebasestorage.app',
    iosBundleId: 'com.example.hotelmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDI8uNO-RMyHBRxtVFzkR_Pv3SRI9SAqC0',
    appId: '1:591172655321:ios:e3d0279007225fe9c1c6c8',
    messagingSenderId: '591172655321',
    projectId: 'hostelmate-e15a4',
    storageBucket: 'hostelmate-e15a4.firebasestorage.app',
    iosBundleId: 'com.example.hotelmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEgOBFCQiYeO7FlkPrvArHRTtYrImFsJY',
    appId: '1:591172655321:web:253011feadee548ec1c6c8',
    messagingSenderId: '591172655321',
    projectId: 'hostelmate-e15a4',
    authDomain: 'hostelmate-e15a4.firebaseapp.com',
    storageBucket: 'hostelmate-e15a4.firebasestorage.app',
    measurementId: 'G-DFTF1P6DM2',
  );

}